apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-lightspeed-operator
  annotations:
    policy.open-cluster-management.io/standards: AI Assistant
    policy.open-cluster-management.io/categories: OpenShift
    policy.open-cluster-management.io/controls: Lightspeed
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-lightspeed-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-lightspeed
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-lightspeed-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: lightspeed-operator
            namespace: openshift-lightspeed
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - lightspeed-operator.v1.0.7
          operatorGroup:
            name: lightspeed-og
            namespace: openshift-lightspeed
            targetNamespaces:
              - openshift-lightspeed