apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/instance: acm-dev-policies
  name: dev
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: dev
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: dev
