apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  labels:
    app.kubernetes.io/instance: acm-dev-policies
  name: dev
spec:
  description: dev policies.
  policies:
    - bootstrap-openshift-gitops-dev
    - kubeletconfig
    - banners-dev
