apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cost-management-operator
  annotations:
    policy.open-cluster-management.io/standards: FinOps
    policy.open-cluster-management.io/categories: Reporting
    policy.open-cluster-management.io/controls: Cost Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cost-management-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                  apiVersion: v1                    
                  kind: Namespace
                  metadata:
                    labels:
                      argocd.argoproj.io/managed-by: openshift-gitops
                    name: costmanagement-metrics-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-cost-management-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: costmanagement-metrics-operator
            namespace: costmanagement-metrics-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          operatorGroup:
            name: costmanagement-metrics-operator
            namespace: costmanagement-metrics-operator
            targetNamespaces:
              - costmanagement-metrics-operator
          versions:
            - costmanagement-metrics-operator.4.2.0

