apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: node-feature-discovery-operator
  annotations:
    policy.open-cluster-management.io/standards: Configuration
    policy.open-cluster-management.io/categories: Discovery
    policy.open-cluster-management.io/controls: Hardware
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: node-feature-discovery-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-nfd
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-node-feature-discovery-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: nfd
            namespace: openshift-nfd
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - nfd.4.20.0-202510221121
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ndf-instance
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-nfd