apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: node-feature-discovery-operator
  annotations:
    policy.open-cluster-management.io/standards: Configuration
    policy.open-cluster-management.io/categories: Discovery
    policy.open-cluster-management.io/controls: Hardware
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: node-feature-discovery-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-nfd
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-node-feature-discovery-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: nfd
            namespace: openshift-nfd
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - nfd.4.20.0-202511250912
          operatorGroup:
            name: nfd-og
            namespace: openshift-nfd
            targetNamespaces:
              - openshift-nfd
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ndf-instance
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: nfd.openshift.io/v1
                kind: NodeFeatureDiscovery
                metadata:
                  name: nfd-instance
                  namespace: openshift-nfd
                spec:
                  enableTaints: false
                  instance: ''
                  operand:
                    imagePullPolicy: IfNotPresent
                    servicePort: 12000
                  prunerOnDelete: false
                  topologyUpdater: false
                  workerConfig:
                    configData: |
                      core:
                      #  labelWhiteList:
                      #  noPublish: false
                        sleepInterval: 60s
                      #  sources: [all]
                      #  klog:
                      #    addDirHeader: false
                      #    alsologtostderr: false
                      #    logBacktraceAt:
                      #    logtostderr: true
                      #    skipHeaders: false
                      #    stderrthreshold: 2
                      #    v: 0
                      #    vmodule:
                      ##   NOTE: the following options are not dynamically run-time 
                      ##          configurable and require a nfd-worker restart to take effect
                      ##          after being changed
                      #    logDir:
                      #    logFile:
                      #    logFileMaxSize: 1800
                      #    skipLogHeaders: false
                      sources:
                      #  cpu:
                      #    cpuid:
                      ##     NOTE: whitelist has priority over blacklist
                      #      attributeBlacklist:
                      #        - "BMI1"
                      #        - "BMI2"
                      #        - "CLMUL"
                      #        - "CMOV"
                      #        - "CX16"
                      #        - "ERMS"
                      #        - "F16C"
                      #        - "HTT"
                      #        - "LZCNT"
                      #        - "MMX"
                      #        - "MMXEXT"
                      #        - "NX"
                      #        - "POPCNT"
                      #        - "RDRAND"
                      #        - "RDSEED"
                      #        - "RDTSCP"
                      #        - "SGX"
                      #        - "SSE"
                      #        - "SSE2"
                      #        - "SSE3"
                      #        - "SSE4.1"
                      #        - "SSE4.2"
                      #        - "SSSE3"
                      #      attributeWhitelist:
                      #  kernel:
                      #    kconfigFile: "/path/to/kconfig"
                      #    configOpts:
                      #      - "NO_HZ"
                      #      - "X86"
                      #      - "DMI"
                        pci:
                          deviceClassWhitelist:
                            - "0200"
                            - "03"
                            - "12"
                          deviceLabelFields:
                      #      - "class"
                            - "vendor"
                      #      - "device"
                      #      - "subsystem_vendor"
                      #      - "subsystem_device"
                      #  usb:
                      #    deviceClassWhitelist:
                      #      - "0e"
                      #      - "ef"
                      #      - "fe"
                      #      - "ff"
                      #    deviceLabelFields:
                      #      - "class"
                      #      - "vendor"
                      #      - "device"
                      #  custom:
                      #    - name: "my.kernel.feature"
                      #      matchOn:
                      #        - loadedKMod: ["example_kmod1", "example_kmod2"]
                      #    - name: "my.pci.feature"
                      #      matchOn:
                      #        - pciId:
                      #            class: ["0200"]
                      #            vendor: ["15b3"]
                      #            device: ["1014", "1017"]
                      #        - pciId :
                      #            vendor: ["8086"]
                      #            device: ["1000", "1100"]
                      #    - name: "my.usb.feature"
                      #      matchOn:
                      #        - usbId:
                      #          class: ["ff"]
                      #          vendor: ["03e7"]
                      #          device: ["2485"]
                      #        - usbId:
                      #          class: ["fe"]
                      #          vendor: ["1a6e"]
                      #          device: ["089a"]
                      #    - name: "my.combined.feature"
                      #      matchOn:
                      #        - pciId:
                      #            vendor: ["15b3"]
                      #            device: ["1014", "1017"]
                      #          loadedKMod : ["vendor_kmod1", "vendor_kmod2"]