apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: entraid
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        clientSecret: "{{ .clientSecret | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: ENTRA_ID_SECRET_VALUE