kind: CostManagementMetricsConfig
apiVersion: costmanagement-metrics-cfg.openshift.io/v1beta1
metadata:
  name: costmanagementmetrics
  namespace: costmanagement-metrics-operator
spec:
  authentication:
    type: service-account
    secret_name: redhat-credentials
  packaging:
    max_reports_to_store: 30
    max_size_MB: 100
  prometheus_config: {}
  source:
    check_cycle: 1440
    create_source: true
    name: Replace Me With Unique Name Per Cluster
  upload:
    upload_cycle: 60
    upload_toggle: true

