apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redhat-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: REDHAT_COSTMGMT_USERNAME
    - secretKey: password
      remoteRef:
        key: REDHAT_COSTMGMT_PASSWORD