apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-pipelines-operator
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: CICD
    policy.open-cluster-management.io/controls: Pipelines
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-pipelines-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: openshift-pipelines-operator-rh
            namespace: openshift-operators
            channel: pipelines-1.18
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - openshift-pipelines-operator-rh.v1.18.0
