kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Pitt Lab IDP
      baseUrl: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca
      
    # auth:
    #   providers:
    #     guest:
    #       dangerouslyAllowOutsideDevelopment: true

    auth:
      environment: production
      session:
        secret: ${BACKEND_AUTH_SECRET}
      providers:
        oidc:
          production:
            metadataUrl: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM} #${AUTH_OIDC_METADATA_URL}
            clientId: ${KEYCLOAK_CLIENTID}
            clientSecret: ${KEYCLOAK_CLIENTSECRET}
            prompt: ${AUTH_OIDC_PROMPT} 
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    signInPage: oidc

    catalog:
     providers:
       keycloakOrg:
         production:
           baseUrl: ${KEYCLOAK_BASE_URL}
           loginRealm: ${KEYCLOAK_REALM}
           realm: ${KEYCLOAK_REALM}
           clientId: ${KEYCLOAK_CLIENTID}
           clientSecret: ${KEYCLOAK_CLIENTSECRET}
           schedule:
            frequency: { minutes: 1 }
            timeout: { minutes: 1 }
            initialDelay: { seconds: 15 }


    backend:
      auth:
        keys:
          - secret: ${BACKEND_AUTH_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca
      cors:
        origin: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca
