apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view-backstage
subjects:
- kind: ServiceAccount
  name: default
  namespace: rhdh
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io