apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-sno
spec:
  mode: deployment
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      
      batch:
        send_batch_size: 256
        timeout: 5s

    exporters:
      otlp_grpc/traces:
        endpoint: tempo-sno:4317
        headers:
          X-Scope-OrgID: "prime"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [ootlp_grpc/traces]