apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        htpasswd: "{{ .htpasswd | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: HTPASSWD