apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-pipelines-operator
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: Coninumous Integratoin
    policy.open-cluster-management.io/controls: Tekton
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-pipelines-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: openshift-pipelines-operator
            namespace: openshift-operators
            channel: pipelines-1.16
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - openshift-pipelines-operator.v1.16.1
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-pipelines-operator
placementRef:
  name: openshift-pipelines-operator
  kind: Placement
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: openshift-pipelines-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: openshift-pipelines-operator
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: role
            operator: In
            values:
              - hub