apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: lvm-storage-operator
  annotations:
    policy.open-cluster-management.io/standards: Cluster Config
    policy.open-cluster-management.io/categories: Storage
    policy.open-cluster-management.io/controls: Block Storage
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-lvm-storage-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-lvm-storage
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-lvm-storage-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: lvms-operator
            namespace: openshift-lvm-storage
            channel: stable-4.20
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - lvms-operator.v4.20.0
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: lvm-storage-cluster
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: lvm.topolvm.io/v1alpha1
                kind: LVMCluster
                metadata:
                  name: default-lvmcluster
                  namespace: openshift-lvm-storage
                spec:
                  storage:
                    deviceClasses:
                      - fstype: xfs
                        thinPoolConfig:
                          chunkSizeCalculationPolicy: Static
                          metadataSizeCalculationPolicy: Host
                          sizePercent: 90
                          name: thin-pool-1
                          overprovisionRatio: 10
                        name: vg1