apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:15-el9
          volumeMounts:
            - mountPath: /data
              name: postgresql-data
          env:
            - name: POSTGRES_USER
              value: keycloakuser
            - name: POSTGRES_PASSWORD
              value: keycloakpass
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data