apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: external-secrets-operator
  annotations:
    policy.open-cluster-management.io/standards: CM Config Management
    policy.open-cluster-management.io/categories: Secrets
    policy.open-cluster-management.io/controls: External Secrets
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: external-secrets-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                  apiVersion: v1                    
                  kind: Namespace
                  metadata:
                    name: external-secrets
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-external-secrets-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: external-secrets-operator
            namespace: openshift-operators
            channel: stable
            source: community-operators
            sourceNamespace: openshift-marketplace
          versions:
            - external-secrets-operator.v0.11.0
# ---
# apiVersion: policy.open-cluster-management.io/v1
# kind: PlacementBinding
# metadata:
#   name: external-secrets-operator
# placementRef:
#   name: external-secrets-operator
#   kind: Placement
#   apiGroup: apps.open-cluster-management.io
# subjects:
#   - name: external-secrets-operator
#     kind: Policy
#     apiGroup: policy.open-cluster-management.io
# ---
# apiVersion: cluster.open-cluster-management.io/v1beta1
# kind: Placement
# metadata:
#   name: external-secrets-operator
# spec:
#   predicates:
#   - requiredClusterSelector:
#       labelSelector:
#         matchExpressions:
#           - key: role
#             operator: In
#             values:
#               - hub