apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-creds-pguser
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          postgres-operator.crunchydata.com/cluster: keycloak-db
          postgres-operator.crunchydata.com/pguser: postgres
      type: Opaque
      data:
        password: "{{ .keycloakDbPassword | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: keycloakDbPassword
      remoteRef:
        key: KEYCLOAK_DB_PASSWORD