apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        POSTGRESQL_USER: "{{ .keycloakDbUser | toString }}"
        POSTGRESQL_PASSWORD: "{{ .keycloakDbPassword | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: keycloakDbUser
      remoteRef:
        key: KEYCLOAK_DB_USER
    - secretKey: keycloakDbPassword
      remoteRef:
        key: KEYCLOAK_DB_PASSWORD