apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-primary.keycloak.svc
    usernameSecret:
      name: keycloak-db-pguser-keycloakuser
      key: user
    passwordSecret:
      name: keycloak-db-pguser-keycloakuser
      key: password
  ingress:
    className: openshift-default
  http:
    tlsSecret: keycloak-cert
  hostname:
    hostname: keycloak.apps.prime.pitt.ca
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 1Gi