apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: registry.redhat.io/rhel9/postgresql-15:latest
          volumeMounts:
            - mountPath: /data
              name: pgdata
          env:
            # - name: POSTGRES_USER
            #   value: testuser
            # - name: POSTGRES_PASSWORD
            #   value: testpassword
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRESQL_DATABASE
              value: keycloak
          envFrom:
            - secretRef:
                name: keycloak-creds
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432