apiVersion: batch/v1
kind: CronJob
metadata:
  name: idle-resources
spec:
  schedule: "0 22 * * *"
  timeZone: Etc/UTC
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: registry.redhat.io/openshift4/ose-cli-artifacts-rhel9:v4.17
              command:
                - /bin/bash
                - -c
                - |
                  echo "Idle services that have the idle label."

                  oc idle -A -l idle

                  echo "Done!"
              imagePullPolicy: Always
              name: idle-resources-job
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
