apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      control-plane: controller-manager
      kuadrant.io/observability: "true"
    name: authorino-operator-monitor
    namespace: kuadrant-system
  spec:
    endpoints:
    - path: /metrics
      port: metrics
      scheme: http
    namespaceSelector: {}
    selector:
      matchLabels:
        control-plane: authorino-operator
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/created-by: dns-operator
      app.kubernetes.io/instance: controller-manager-metrics-monitor
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: servicemonitor
      app.kubernetes.io/part-of: dns-operator
      control-plane: controller-manager
      kuadrant.io/observability: "true"
    name: dns-operator-monitor
    namespace: kuadrant-system
  spec:
    endpoints:
    - path: /metrics
      port: metrics
      scheme: http
    namespaceSelector: {}
    selector:
      matchLabels:
        control-plane: dns-operator-controller-manager
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      control-plane: controller-manager
      kuadrant.io/observability: "true"
    name: kuadrant-authorino-monitor
    namespace: kuadrant-system
  spec:
    endpoints:
    - path: /metrics
      port: http
      scheme: http
    - path: /server-metrics
      port: http
      scheme: http
    namespaceSelector: {}
    selector:
      matchLabels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/part-of: authorino
        control-plane: controller-manager
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      control-plane: controller-manager
      kuadrant.io/observability: "true"
    name: kuadrant-operator-monitor
    namespace: kuadrant-system
  spec:
    endpoints:
    - path: /metrics
      port: metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - kuadrant-system
    selector:
      matchLabels:
        app: kuadrant
        control-plane: controller-manager
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      control-plane: controller-manager
      kuadrant.io/observability: "true"
    name: limitador-operator-monitor
    namespace: kuadrant-system
  spec:
    endpoints:
    - path: /metrics
      port: metrics
      scheme: http
    namespaceSelector: {}
    selector:
      matchLabels:
        control-plane: controller-manager
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    labels:
      kuadrant.io/observability: "true"
    name: istio-pod-monitor
    namespace: kuadrant-gateway
  spec:
    namespaceSelector: {}
    podMetricsEndpoints:
    - bearerTokenSecret:
        key: ""
        name: ""
      interval: 30s
      path: /stats/prometheus
      relabelings:
      - action: keep
        regex: istio-proxy
        sourceLabels:
        - __meta_kubernetes_pod_container_name
      - action: keep
        sourceLabels:
        - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
      - action: replace
        regex: (\\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
        replacement: '[$2]:$1'
        sourceLabels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        targetLabel: __address__
      - action: replace
        regex: (\\d+);((([0-9]+?)(\\.|$)){4})
        replacement: $2:$1
        sourceLabels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_ip
        targetLabel: __address__
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        sourceLabels:
        - __meta_kubernetes_namespace
        targetLabel: namespace
      - action: replace
        sourceLabels:
        - __meta_kubernetes_pod_name
        targetLabel: pod_name
    selector:
      matchExpressions:
      - key: istio-prometheus-ignore
        operator: DoesNotExist
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    labels:
      app: limitador
      kuadrant.io/observability: "true"
    name: kuadrant-limitador-monitor
    namespace: kuadrant-system
  spec:
    namespaceSelector:
      matchNames:
      - kuadrant-system
    podMetricsEndpoints:
    - bearerTokenSecret:
        key: ""
        name: ""
      path: /metrics
      port: http
      scheme: http
    selector:
      matchLabels:
        app: limitador
        limitador-resource: limitador
kind: List
metadata: {}
