apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    kuadrant.io/observability: "true"
  name: kuadrant-authorino-monitor
  namespace: kuadrant-system
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  - path: /server-metrics
    port: http
    scheme: http
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/part-of: authorino
      control-plane: controller-manager
