apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-openshift-gitops-operator
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: GitOps
    policy.open-cluster-management.io/controls: OpenShift GitOpss Operator
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-gitops-operator
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: openshift-gitops-extended-clusterrolebinding
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
                subjects:
                  - kind: ServiceAccount
                    name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-gitops-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: openshift-gitops-operator
            namespace: openshift-gitops-operator
            channel: gitops-1.14
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: openshift-gitops-operator.v1.14.2
          versions:
            - openshift-gitops-operator.v1.14.2
# ---
# apiVersion: policy.open-cluster-management.io/v1
# kind: PlacementBinding
# metadata:
#   name: binding-policy-openshift-gitops-operator
# placementRef:
#   name: placement-policy-openshift-gitops-operator
#   kind: PlacementRule
#   apiGroup: apps.open-cluster-management.io
# subjects:
#   - name: policy-openshift-gitops-operator
#     kind: Policy
#     apiGroup: policy.open-cluster-management.io
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: PlacementRule
# metadata:
#   name: placement-policy-openshift-gitops-operator
# spec:
#   clusterConditions:
#     - status: 'True'
#       type: ManagedClusterConditionAvailable
#   clusterSelector:
#     matchExpressions:
#       - key: vendor
#         operator: In
#         values:
#           - "OpenShift"