apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rhacs-operator
  annotations:
    policy.open-cluster-management.io/standards: Security
    policy.open-cluster-management.io/categories: Kubernetes
    policy.open-cluster-management.io/controls: Cluster Security
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                  apiVersion: v1                    
                  kind: Namespace
                  metadata:
                    name: rhacs-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-rhacs-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: rhacs-operator
            namespace: rhacs-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - rhacs-operator.v4.7.3

