apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: route53-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        access-key-id: "{{ .r53SecretKey | toString }}"
        secret-access-key: "{{ .r53SecretValue | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: r53SecretKey
      remoteRef:
        key: ROUTE53_SECRET_KEY
    - secretKey: r53SecretValue
      remoteRef:
        key: ROUTE53_SECRET_VALUE