namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: openshift-oauth-config
    spec:
      source:
        path: gitops/cluster-config/openshift-oauth/overlays/sno