apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  resourceProfile: "lean"
  enableCephTools: false
  allowRemoteStorageConsumers: false
  managedResources:
    cephObjectStoreUsers: {}
    cephCluster: {}
    cephBlockPools: {}
    cephNonResilientPools: {}
    cephObjectStores: {}
    cephFilesystems: {}
    cephRBDMirror: {}
    cephToolbox: {}
    cephDashboard: {}
    cephConfig: {}
  mirroring: {}
  multiCloudGateway:
    dbStorageClassName: lvms-vg1
    reconcileStrategy: standalone
    disableLoadBalancerService: true
  resources:
    noobaa-core:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
    noobaa-db:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
    noobaa-endpoint:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 2Gi