apiVersion: v1
kind: Secret
metadata:
  name: rhdh-token
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Validate=false
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token