apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: kuadrant-gateway-tls
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kuadrant-gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod