apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: azure-repose-https-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      stringData:
        type: git
        url: https://dev.azure.com
      data:
        username: pittar-demo
        password: "{{ .personalAccessToken | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: personalAccessToken
      remoteRef:
        key: ADO_PERSONAL_ACCESS_TOKEN
