apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: kafka-streams-operator
  annotations:
    policy.open-cluster-management.io/standards: Middleware
    policy.open-cluster-management.io/categories: Event Streaming
    policy.open-cluster-management.io/controls: Kafka
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: kafka-streams-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: kafka-streams-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-kafka-streams-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: amq-streams
            namespace: kafka-streams
            channel: amq-streams-2.8.x
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - amqstreams.v2.8.0-0-0.1738265624.p
