apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kuadrant-prime
spec:
  observability:
    enable: true
    tracing:
      defaultEndpoint: rpc://otel-sno-collector.tempo-observability.svc.cluster.local:4317
      insecure: true
    dataPlane:
      defaultLevels:
        - info: "true"
      httpHeaderIdentifier: "traceparent" # W3C Trace Context standard