commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - github.com/redhat-cop/gitops-catalog/external-secrets-operator/operator/overlays/stable
  - github.com/redhat-cop/gitops-catalog/external-secrets-operator/instance/overlays/default
  - cluster-secret-store.yaml