apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: local-cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    cluster.open-cluster-management.io/clusterset: prime
    role: hub
