apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        alertmanager.yaml: "{{ .alertmanagerMain | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: alertmanagerMain
      remoteRef:
        key: ALERTMANAGER_MAIN