apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rhacs-central
  annotations:
    policy.open-cluster-management.io/standards: Security
    policy.open-cluster-management.io/categories: Kubernetes
    policy.open-cluster-management.io/controls: RHACS Central
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: stackrox
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central-cert
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cert-manager.io/v1
                kind: Certificate
                metadata:
                  annotations:
                    argocd.argoproj.io/sync-wave: "1"
                  name: central-default-tls-cert
                  namespace: stackrox
                spec:
                  isCA: false
                  commonName: "central-stackrox.apps.prime.pitt.ca" 
                  secretName: rhacs-central-cert 
                  dnsNames:
                  - "central-stackrox.apps.prime.pitt.ca" 
                  issuerRef:
                    name: letsencrypt-prod 
                    kind: ClusterIssuer
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  name: stackrox-central-services
                  namespace: stackrox
                spec:
                  central:
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                  egress:
                    connectivityPolicy: Online
                  scanner:
                    analyzer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 1
                        minReplicas: 1
                        replicas: 1
                    scannerComponent: Enabled
