apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rhacs-central
  annotations:
    policy.open-cluster-management.io/standards: Security
    policy.open-cluster-management.io/categories: Kubernetes
    policy.open-cluster-management.io/controls: RHACS Central
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: stackrox
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central-cert
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cert-manager.io/v1
                kind: Certificate
                metadata:
                  annotations:
                    argocd.argoproj.io/sync-wave: "1"
                  name: central-default-tls-cert
                  namespace: stackrox
                spec:
                  isCA: false
                  commonName: "central-stackrox.apps.prime.pitt.ca" 
                  secretName: central-default-tls-cert 
                  dnsNames:
                  - "central-stackrox.apps.prime.pitt.ca" 
                  issuerRef:
                    name: letsencrypt-prod 
                    kind: ClusterIssuer
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  name: stackrox-central-services
                  namespace: stackrox
                spec:
                  central:
                    db:
                      isEnabled: Default
                      resources:
                        limits:
                          cpu: '4'
                          memory: 8Gi
                        requests:
                          cpu: 250m
                          memory: 4Gi
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                    resources:
                      limits:
                        memory: 4Gi
                      requests:
                        cpu: 500m
                        memory: 2Gi
                  egress:
                    connectivityPolicy: Online
                  scannerV4:
                    indexer:
                      scaling:
                        autoScaling: Disabled
                        replicas: 1
                      resources:
                        limits:
                          memory: 1Gi
                        requests:
                          cpu: 250m
                          memory: 500Mi
                    matcher:
                      scaling:
                        autoScaling: Disabled
                        replicas: 1
                      resources:
                        requests:
                          cpu: 250m
                          memory: 1500Mi
                    scannerComponent: Enabled
                  scanner:
                    scannerComponent: Disabled
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacs-central-init-bundle-sa
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: create-cluster-init
                  namespace: stackrox
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: create-cluster-init
                rules:
                  - apiGroups:
                    - app.k8s.io
                    resources:
                    - applications
                    verbs:
                    - '*'
                  - apiGroups:
                    - apps.open-cluster-management.io
                    resources:
                    - '*'
                    verbs:
                    - '*'
                  - apiGroups:
                    - ""
                    resources:
                    - configmaps
                    - secrets
                    - namespaces
                    verbs:
                    - '*'
                  - apiGroups:
                      - route.openshift.io
                    resources:
                      - routes
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - platform.stackrox.io
                    resources:
                      - '*'
                    verbs:
                      - '*'
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: create-cluster-init
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: create-cluster-init
                subjects:
                  - kind: ServiceAccount
                    name: create-cluster-init
                    namespace: stackrox
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: create-cluster-init-admin
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-admin
                subjects:
                  - kind: ServiceAccount
                    name: create-cluster-init
                    namespace: stackrox
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central-init-bundle
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: batch/v1
                kind: Job
                metadata:
                  name: create-cluster-init-bundle
                  namespace: stackrox
                spec:
                  template:
                    spec:
                      containers:
                        - image: quay.io/pittar/acs-deploy-bundle-job:new-acm-process
                          env:
                          - name: PASSWORD
                            valueFrom:
                              secretKeyRef:
                                name: central-htpasswd
                                key: password
                          command:
                            - /bin/bash
                            - -c
                            - |
                              #!/usr/bin/env bash

                              oc project stackrox
                              bash deploy-bundle.sh -i bundle.yaml

                              echo "Complete"
                          imagePullPolicy: Always
                          name: create-acs-init-bundle
                      dnsPolicy: ClusterFirst
                      restartPolicy: Never
                      serviceAccount: create-cluster-init
                      serviceAccountName: create-cluster-init
                      terminationGracePeriodSeconds: 30
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central-console-link
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: acs-central
                spec:
                  applicationMenu:
                    section: Applications
                  location: ApplicationMenu
                  text: Central - Advanced Cluster Security
                  href: https://central-stackrox.apps.prime.pitt.ca/