apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cert-manager-operator
  annotations:
    policy.open-cluster-management.io/standards: CM Config Management
    policy.open-cluster-management.io/categories: Certificates
    policy.open-cluster-management.io/controls: Certificate Management
spec:
  remediationAction: enforce
  disabled: false
  hubTemplateOptions:
    serviceAccountName: global
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cert-manager-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                  apiVersion: v1                    
                  kind: Namespace
                  metadata:
                    labels:
                      argocd.argoproj.io/managed-by: openshift-gitops
                    name: cert-manager-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-cert-manager-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: openshift-cert-manager-operator
            namespace: cert-manager-operator
            channel: stable-v1.14
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - openshift-cert-manager-operator.v1.14

