apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  labels:
    app.kubernetes.io/instance: acm-prod-policies
  name: prod
spec:
  description: prod policies.
  policies:
    - openshift-gitops-operator
