apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: apicurio-registry-operator
  annotations:
    policy.open-cluster-management.io/standards: Registry
    policy.open-cluster-management.io/categories: Schema Registry
    policy.open-cluster-management.io/controls: Apicurio
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: apicurio-registry-operator-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: apicurio-registry-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-apicurio-registry-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: apicurio-registry-3
            namespace: apicurio-registry-operator
            channel: 3.2.x
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - apicurio-registry-3.v3.2.6-r1
