resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: default
    spec:
      source:
        path: gitops/cluster-services/connectivitylink/gateways/overlays/default-prime