apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  labels:
    app.kubernetes.io/instance: acm-global-policies
  name: global
spec:
  description: Global policies.
  policies:
    - default-storageclass
    - openshift-gitops-operator
    - external-secrets-operator
    - cert-manager-operator
    - cost-management-operator
    - networkpolicy-deny-all
    - networkpolicy-allow-ingress
