apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/instance: acm-global-policies
  name: global
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: global
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: global
