apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-allocatable
  namespace: openshift-config-operator
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""  # change the label to find the nodes with heavy workload
  kubeletConfig:
    systemReserved:
      cpu: 500m        # change the CPU if needed
      memory: 2148Mi   # change the memory if needed