apiVersion: extensions.kuadrant.io/v1alpha1
kind: TelemetryPolicy
metadata:
  name: kuadrant-gateway-user-metrics
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: kuadrant-gateway
  metrics:
    default:
      labels:
        user: 'has(auth.identity) && has(auth.identity.userid) ? auth.identity.userid : ""'
        group: 'has(auth.identity) && has(auth.identity.groups) ? string(auth.identity.groups) : ""'