apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: kuadrant-gateway-podmonitor
  labels:
    metrics: workload-monitor
spec:
  selector:
    matchLabels:
      kuadrant.io/gateway: "true"
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s