apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kuadrant-gateway-monitor
  labels:
    metrics: workload-monitor
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: kuadrant-gateway
  endpoints:
    - port: status-port
      path: /stats/prometheus
      interval: 30s
      scheme: http
