apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: kuadrant-gateway-podmonitor
  labels:
    metrics: workload-monitor
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: kuadrant-gateway
  podMetricsEndpoints:
    - port: http-monitoring
      path: /stats/prometheus
      interval: 30s
      scheme: http