apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: acs-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        ACS_API_URL: "{{ .ACS_API_URL | toString }}"
        ACS_API_KEY: "{{ .ACS_API_KEY | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: ACS_API_URL
      remoteRef:
        key: ACS_API_URL
    - secretKey: ACS_API_KEY
      remoteRef:
        key: ACS_API_KEY
