apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ado-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        AZURE_CLIENT_ID: "{{ .azureClientId | toString }}"
        AZURE_CLIENT_SECRET: "{{ .azureClientSecret | toString }}"
        AZURE_TENANT_ID: "{{ .azureTenantId | toString }}"
        PERSONAL_ACCESS_TOKEN: "{{ .personalAccessToken | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: azureClientId
      remoteRef:
        key: ADO_AZURE_CLIENT_ID
    - secretKey: azureClientSecret
      remoteRef:
        key: ADO_AZURE_CLIENT_SECRET
    - secretKey: azureTenantId
      remoteRef:
        key: ADO_AZURE_TENANT_ID
    - secretKey: personalAccessToken
      remoteRef:
        key: ADO_PERSONAL_ACCESS_TOKEN