kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Home Lab IDP
      baseUrl: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca

    argocd:
      waitCycles: 25
      secure: false
      projectSettings:
        # Sets the allowed resources at the cluster level
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
        # Sets the allowed resources at the namespace level
        namespaceResourceWhitelist:
          - group: '*'
            kind: '*'
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: openshift-gitops
              url: https://openshift-gitops-server-openshift-gitops.apps-crc.testing
              username: ${ARGOCD_ADMIN_USER}
              password: ${ARGOCD_ADMIN_PASSWORD}

    kubernetes:
      clusterLocatorMethods:
        - clusters:
          - authProvider: serviceAccount
            name: ${K8S_CLUSTER_NAME}
            serviceAccountToken: ${K8S_CLUSTER_TOKEN}
            url: ${K8S_CLUSTER_URL}
            skipTLSVerify: true
            skipMetricsLookup: true
          type: config
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelines'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
        - group: 'route.openshift.io'
          apiVersion: 'v1'
          plural: 'routes'
      serviceLocatorMethod:
          type: multiTenant

    azureDevOps:
      host: dev.azure.com
      token: ${PERSONAL_ACCESS_TOKEN}
      organization: pittar-demos

    integrations:
      azure:
        - host: dev.azure.com
          credentials:
            - personalAccessToken: ${PERSONAL_ACCESS_TOKEN}

    signInPage: oidc

    auth:
      environment: production
      session:
        secret: abc123supers3cr3t
      providers:
        oidc:
          production:
            metadataUrl: ${KEYCLOAK_BASE_URL}/auth/realms/${KEYCLOAK_REALM}
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            prompt: auto
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName

    dangerouslyAllowSignInWithoutUserInCatalog: true

    catalog:
      rules:
        - allow: [Component, System,   Group, Resource, Location, Template, API]
      locations:
        - type: url
          target: https://dev.azure.com/pittar-demos/rhdh-demo/_git/software-templates?path=/showcase-templates.yaml
      providers:
        keycloakOrg:
          default:
            baseUrl: ${KEYCLOAK_BASE_URL}/auth
            loginRealm: ${KEYCLOAK_REALM}
            realm: ${KEYCLOAK_REALM}
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 1 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }

    # permission:
    #   enabled: true
    #   rbac:
    #     #policies-csv-file: ./rbac-policy.csv
    #     admin:
    #       users:
    #         - name: user:default/homelab-admin

    backend:
      auth:
        keys:
          - secret: abc123supers3cr3t
      baseUrl: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca
      cors:
        origin: https://backstage-developer-hub-rhdh.apps.lab.pitt.ca
