apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
        - name: ado-secrets
        - name: rhsso-secret
    replicas: 1
    route:
      enabled: true
  # deployment:
  #   patch:
  #     spec:
  #       template:
  #         spec:
  #           volumes:
  #             - $patch: replace
  #               name: dynamic-plugins-root
  #               persistentVolumeClaim:
  #                 claimName: dynamic-plugins-root
  database:
    enableLocalDb: true