apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
        - name: ado-secrets
        - name: sso-secret
      envs:
        # Only needed because gitea uses a self-signed cert.
        # Can be removed once OCP API gets a good cert.
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        # - name: LOG_LEVEL
        #   value: debug
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policy
    replicas: 1
    route:
      enabled: true
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
  database:
    enableLocalDb: true