apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: github-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        RHDH_GITHUB_ORGANIZATION: "{{ .githubOrg | toString }}"
        RHDH_GITHUB_APP_ID: "{{ .githubAppId | toString }}"
        RHDH_GITHUB_APP_CLIENT_ID: "{{ .githubClientId | toString }}"
        RHDH_GITHUB_APP_CLIENT_SECRET: "{{ .githubClientSecret | toString }}"
        RHDH_GITHUB_APP_PRIVATE_KEY: "{{ .githubPrivateKey | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: githubOrg
      remoteRef:
        key: RHDH_GITHUB_ORG
    - secretKey: githubAppId
      remoteRef:
        key: RHDH_GITHUB_APPID
    - secretKey: githubClientId
      remoteRef:
        key: RHDH_GITHUB_CLIENTID
    - secretKey: githubClientSecret
      remoteRef:
        key: RHDH_GITHUB_SECRET
    - secretKey: githubPrivateKey
      remoteRef:
        key: RHDH_GITHUB_PEM