apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: gitops-prod-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        ARGOCD_PROD_ADMIN_USER: "{{ .gitopsUser | toString }}"
        ARGOCD_PROD_ADMIN_PASSWORD: "{{ .gitopsPassword | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: gitopsUser
      remoteRef:
        key: ARGOCD_PROD_ADMIN_USER
    - secretKey: gitopsPassword
      remoteRef:
        key: ARGOCD_PROD_ADMIN_USER
