apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sso-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        KEYCLOAK_BASE_URL: "{{ .baseUrl | toString }}"
        KEYCLOAK_CLIENT_ID: "{{ .clientId | toString }}"
        KEYCLOAK_CLIENT_SECRET: "{{ .clientSecret | toString }}"
        KEYCLOAK_REALM: "{{ .realm | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: RHDH_KEYCLOAK_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: RHDH_KEYCLOAK_SECRET
    - secretKey: realm
      remoteRef:
        key: RHDH_KEYCLOAK_REALM
    - secretKey: baseUrl
      remoteRef:
        key: KEYCLOAK_BASE_URL