kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    # Developers
    p, role:default/developers, catalog.entity.read, read, allow
    p, role:default/developers, catalog.location.read, read, allow
    p, role:default/developers, topology.view.read, read, allow
    # Team Lead 
    p, role:default/teamleads, catalog.entity.read, read, allow
    p, role:default/teamleads, catalog.entity.create, create, allow
    p, role:default/teamleads, catalog.location.read, read, allow
    p, role:default/teamleads, catalog.location.create, create, allow
    p, role:default/teamleads, topology.view.read, read, allow
    p, role:default/teamleads, scaffolder.action.execute, use, allow
    p, role:default/teamleads, scaffolder.template.parameter.read, read, allow
    p, role:default/teamleads, scaffolder.template.step.read, read, allow
    p, role:default/teamleads, scaffolder.task.create, create, allow
    p, role:default/teamleads, scaffolder.task.cancel, use, allow
    p, role:default/teamleads, scaffolder.task.read, read, allow
    # Role assignments (to group)
    g, group:default/developers, role:default/developers
    g, group:default/teamleads, role:default/teamleads