apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: default-view-backstage
subjects:
- kind: ServiceAccount
  name: default
  namespace: rhdh
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io