apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: default-backstage-secrets
spec:
  template:
    spec:
      containers:
        - image: quay.io/pittar/toolkit:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Create a Red Hat org. Wait 2min for Gitea to fully init."

              oc create secret generic rhdh-secrets  \
                --from-literal=ARGOCD_ADMIN_USER=admin \
                --from-literal=ARGOCD_ADMIN_PASSWORD=$(oc extract secret/openshift-gitops-cluster -n openshift-gitops --to=-) \
                --from-literal=K8S_CLUSTER_NAME=homelab \
                --from-literal=K8S_CLUSTER_URL=https://api.prime.pitt.ca:6443 \
                --from-literal=K8S_CLUSTER_TOKEN=$(oc get secret rhdh-token -n rhdh -o jsonpath="{.data['token']}" | base64 -d) \
                -n rhdh

              echo "Done"
          imagePullPolicy: Always
          name: default-backstage-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30