apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
  containerRegistry: {}
  devEnvironments:
    #disableContainerRunCapabilities: false
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: 3600
    maxNumberOfWorkspacesPerUser: -1
    maxNumberOfRunningWorkspacesPerUser: 3
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-user
    samples:
      - displayName: "Skupper Demo"
        description: "Skupper frontend and backend components."
        tags: ["java", "skupper", "yaml"]
        icon: "https://github.com/pittar-demos/devspaces-custom-udi/blob/5f5c484f02ec1eb23d42b8c4ec510ab153903654/samples/devfiles/skupper-demo/skupper.png"
        url: "https://github.com/pittar-demos/devspaces-custom-udi/blob/5f5c484f02ec1eb23d42b8c4ec510ab153903654/samples/devfiles/skupper-demo/.devfile.yaml"
    defaultComponents:
      - name: tools
        container:
          image: quay.io/pittar/custom-udi-demo:latest
          memoryLimit: 4Gi
          memoryRequest: 1Gi
          cpuLimit: "1"
          cpuRequest: 100m
          mountSources: true
  gitServices: {}
  networking:
    auth:
      gateway:
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO
