apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: opencode-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        annotations:
          che.eclipse.org/mount-as: file
          che.eclipse.org/mount-path: /home/user/.config/opencode
        labels:
          app.kubernetes.io/component: workspaces-config
          controller.devfile.io/mount-to-devworkspace: 'true'
          controller.devfile.io/watch-secret: 'true'
      type: Opaque
      data:
        opencode.jsonc: |
          "{{ .opencodeConfig | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: opencodeConfig
      remoteRef:
        key: OPENCODE_JSONC
