apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: opencode-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          controller.devfile.io/mount-to-devworkspace: 'true'
          controller.devfile.io/watch-secret: 'true'
        annotations:
          controller.devfile.io/mount-path: '/data/opencode'
          #che.eclipse.org/mount-as: file
      type: Opaque
      data:
        opencode.jsonc: |
          {{ .opencodeConfig | toString }}
    creationPolicy: Owner
  data:
    - secretKey: opencodeConfig
      remoteRef:
        key: OPENCODE_JSONC
