apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: opencode-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/component: workspaces-config
          app.kubernetes.io/managed-by: devspaces-operator
          app.kubernetes.io/part-of: che.eclipse.org
          controller.devfile.io/mount-to-devworkspace: 'true'
          controller.devfile.io/watch-secret: 'true'
        annotations:
          che.eclipse.org/mount-path: /data/opencode
          che.eclipse.org/mount-as: file
      type: Opaque
      data:
        opencode.jsonc: |
          "{{ .opencodeConfig | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: opencodeConfig
      remoteRef:
        key: OPENCODE_JSONC
