apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      data:
        apitoken: "{{ .apitoken | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: apitoken
      remoteRef:
        key: MAAS_LIGHTSPEED_TOKEN