apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: minimax-m2
        name: red_hat_openshift_ai
        type: rhoai_vllm
        url: 'https://maas-rhdp.apps.maas.redhatworkshops.io/v1'
  ols:
    defaultModel: minimax-m2
    defaultProvider: red_hat_openshift_ai
    introspectionEnabled: true
    logLevel: INFO
