apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: granite-3-3-8b-instruct
        name: red_hat_openshift_ai
        type: rhoai_vllm
        url: 'https://granite-3-3-8b-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1'
  ols:
    defaultModel: granite-3-3-8b-instruct
    defaultProvider: red_hat_openshift_ai
    introspectionEnabled: true
    logLevel: INFO
