namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: connectivitylink
    spec:
      source:
        path: gitops/cluster-services/connectivitylink/kuadrant/prime