apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
  name: cluster
spec:
  identityProviders:
    - name: htpasswd 
      mappingMethod: claim 
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd
