apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kuadrant-authorino-monitor
  labels:
    metrics: workload-monitor 
spec:
  selector:
    matchLabels:
      # Matches the exact unique labels from your authorino-controller-metrics service
      authorino-resource: authorino
      app.kubernetes.io/component: metrics
  endpoints:
    - port: http # Matches name: http from your service spec
      path: /metrics
      interval: 30s
      scheme: http