apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kuadrant-opeartor-monitor
  labels:
    metrics: workload-monitor 
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: kuadrant
      control-plane: controller-manager