apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: kuadrant-limitador-monitor
  labels:
    metrics: workload-monitor 
spec:
  selector:
    matchLabels:
      limitador-resource: limitador
      app.kubernetes.io/name: limitador
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http