apiVersion: monitoring.rhobs/v1
kind: PodMonitor
metadata:
  name: kuadrant-limitador-monitor
  labels:
    metrics: workload-monitor 
spec:
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
      name: ""
    path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app: limitador
      limitador-resource: limitador