apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/instance: acm-prime-policies
  name: prime
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: prime
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: prime
