apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  labels:
    app.kubernetes.io/instance: acm-prime-policies
  name: prime
spec:
  description: Prime cluster policies.
  policies:
    - bootstrap-rhacm-gitops
    - bootstrap-openshift-gitops
