apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  labels:
    app.kubernetes.io/instance: acm-prime-policies
  name: prime
spec:
  description: Prime cluster policies.
  policies:
    - banners-prime
    - global-policy-namespace-rbac
    - prime-policy-namespace-rbac
    - bootstrap-rhacm-gitops
    - bootstrap-openshift-gitops-prime
    - developer-hub-operator
    - openshift-pipelines-operator
    - keycloak-operator
    - devspaces-operator
    - crunchy-postgres-operator-v5-7
    - openshift-lightspeed-operator
    - openshift-virtualization-operator
    - kubeletconfig
    - rhacs-central
