apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: external-secrets-operator
  annotations:
    policy.open-cluster-management.io/standards: CM Config Management
    policy.open-cluster-management.io/categories: Secrets
    policy.open-cluster-management.io/controls: External Secrets
spec:
  remediationAction: enforce
  disabled: false
  hubTemplateOptions:
    serviceAccountName: prime
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: external-secrets-namespace
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                  apiVersion: v1                    
                  kind: Namespace
                  metadata:
                    labels:
                      argocd.argoproj.io/managed-by: openshift-gitops
                    name: external-secrets
    # - objectDefinition:
    #     apiVersion: v1
    #     kind: Secret
    #     metadata:
    #       name: eso-token-cluster-homelab
    #       namespace: external-secrets
    #     type: Opaque
    #     data:
    #       dopplerToken: '{{hub fromSecret "external-secrets" "doppler-token" "dopplerToken" hub}}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-external-secrets-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            name: external-secrets-operator
            namespace: openshift-operators
            channel: stable
            source: community-operators
            sourceNamespace: openshift-marketplace
          versions:
            - external-secrets-operator.v0.11.0
    # - objectDefinition:
    #     apiVersion: external-secrets.io/v1beta1
    #     kind: ClusterSecretStore
    #     metadata:
    #       name: doppler
    #     spec:
    #       provider:
    #         doppler:
    #           auth:
    #             secretRef:
    #               dopplerToken:
    #                 name: eso-token-cluster-homelab
    #                 key: dopplerToken
    #                 namespace: external-secrets
