apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/instance: acm-appservices-policies
  name: appservices
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: appservices
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: appservices
