apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    # dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    # extraEnvs:
    #   secrets:
    #     - name: rhdh-secrets
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true